name: Basic yaml file

on: 
  push: 

jobs: 
  testing: 
    name: testing file 
    runs-on: ubuntu-latest
    steps: 
      - name: reading the repo files 
        uses: actions/checkout@v4
      - name: listing files 
        run: |
              echo "welcome to GitHub Actions"
              ls -la
              cat index.html
