name : shell yaml 
on : 
  workflow_dispatch 

jobs : 
  my_shell : 
    name : configuring cowsay 
    runs-on : ubuntu-latest
    steps : 
      - name : checkout repo 
        uses : actions/checkout@v4
      - name : using shell script 
        run : | 
                chmod +x cowsayshellscript.sh
                ./cowsayshellscript.sh
